package com.project.cfgames.entities.enums;

public enum StatusPedido {
    EM_PROCESSAMENTO,
    PAGAMENTO_APROVADO,
    PAGAMENTO_REPROVADO,
    EM_TRANSITO,
    ENTREGUE,
    TROCA_SOLICITADA,
    TROCA_APROVADA,
    TROCA_REPROVADA,
    PRODUTOS_TROCA_RECEBIDOS,
    TROCA_FINALIZADA,
    TROCA_CANCELADA,
    CANCELADO;
}
